package com.hsjry.user.facade.pojo;

import com.hsjry.user.facade.pojo.enums.EnumResellerType;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Created by zhangxianli on 2018/6/6.
 */
public class CustomerMgrSubmitInfoPojo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer_mgr_submit_info.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer_mgr_submit_info.USER_DRAFT_INFO_ID
     *
     * @mbggenerated
     */
    private String userDraftInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer_mgr_submit_info.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer_mgr_submit_info.MOBILE
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer_mgr_submit_info.RESELLER_ID
     *
     * @mbggenerated
     */
    private String resellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer_mgr_submit_info.RESELLER_NAME
     *
     * @mbggenerated
     */
    private String resellerName;

    /**
     * 经销商类型
     */
    private EnumResellerType enumResellerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer_mgr_submit_info.PRODUCT_ID
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer_mgr_submit_info.AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer_mgr_submit_info.PAYMENT
     *
     * @mbggenerated
     */
    private BigDecimal payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer_mgr_submit_info.APPLY_AMOUT
     *
     * @mbggenerated
     */
    private BigDecimal applyAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer_mgr_submit_info.APPLY_TIME
     *
     * @mbggenerated
     */
    private Date applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer_mgr_submit_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer_mgr_submit_info.ID_NO
     *
     * @mbggenerated
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer_mgr_submit_info.STATE
     *
     * @mbggenerated
     */
    private Byte state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_customer_mgr_submit_info.ID
     *
     * @return the value of user_customer_mgr_submit_info.ID
     *
     * @mbggenerated
     */

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUserDraftInfoId() {
        return userDraftInfoId;
    }

    public void setUserDraftInfoId(String userDraftInfoId) {
        this.userDraftInfoId = userDraftInfoId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getResellerId() {
        return resellerId;
    }

    public void setResellerId(String resellerId) {
        this.resellerId = resellerId;
    }

    public String getResellerName() {
        return resellerName;
    }

    public void setResellerName(String resellerName) {
        this.resellerName = resellerName;
    }

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public BigDecimal getPayment() {
        return payment;
    }

    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    public BigDecimal getApplyAmount() {
        return applyAmount;
    }

    public void setApplyAmount(BigDecimal applyAmount) {
        this.applyAmount = applyAmount;
    }

    public Date getApplyTime() {
        return applyTime;
    }

    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getIdNo() {
        return idNo;
    }

    public void setIdNo(String idNo) {
        this.idNo = idNo;
    }

    public Byte getState() {
        return state;
    }

    public void setState(Byte state) {
        this.state = state;
    }

    public EnumResellerType getEnumResellerType() {
        return enumResellerType;
    }

    public void setEnumResellerType(EnumResellerType enumResellerType) {
        this.enumResellerType = enumResellerType;
    }
}
