/**
 * @System: 消费金融
 * Copyright (c) 2017杭州恒生云融网络有限公司-版权所有
 */
package com.hsjry.user.facade.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * @author: xuxd14949
 * Date: 2018/5/22
 * Time: 11:11
 * @mail: xuxd14949@hundsun.com
 * @version: 2.0
 */

public class UserFaceAuthPojo implements Serializable {

    private static final long serialVersionUID = -877344821712756013L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_face_auth.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_face_auth.CLIENT_NAME
     *
     * @mbggenerated
     */
    private String clientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_face_auth.ID_NO
     *
     * @mbggenerated
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_face_auth.ID_KIND
     *
     * @mbggenerated
     */
    private String idKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_face_auth.RESULT_TYPE
     *
     * @mbggenerated
     */
    private String resultType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_face_auth.RESULT_CONTENT
     *
     * @mbggenerated
     */
    private String resultContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_face_auth.APPLY_DATE
     *
     * @mbggenerated
     */
    private Date applyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_face_auth.OTHER_INFO
     *
     * @mbggenerated
     */
    private String otherInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_face_auth.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_face_auth.CREATOR
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_face_auth.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_face_auth.MODIFIER
     *
     * @mbggenerated
     */
    private String modifier;

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getClientName() {
        return clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    public String getIdNo() {
        return idNo;
    }

    public void setIdNo(String idNo) {
        this.idNo = idNo;
    }

    public String getIdKind() {
        return idKind;
    }

    public void setIdKind(String idKind) {
        this.idKind = idKind;
    }

    public String getResultType() {
        return resultType;
    }

    public void setResultType(String resultType) {
        this.resultType = resultType;
    }

    public String getResultContent() {
        return resultContent;
    }

    public void setResultContent(String resultContent) {
        this.resultContent = resultContent;
    }

    public Date getApplyDate() {
        return applyDate;
    }

    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    public String getOtherInfo() {
        return otherInfo;
    }

    public void setOtherInfo(String otherInfo) {
        this.otherInfo = otherInfo;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getCreator() {
        return creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getModifier() {
        return modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier;
    }
}

