spring:
    profiles:
        active: test
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    data:
        mongodb:
              uri: mongodb://sit1:sit2019!@192.168.0.230:27017,192.168.0.227:27017,192.168.0.220:27017
              database: pangolin_dataimp_db
    rabbitmq:
        username: admin
        password: admin
        host: 192.192.0.49
        virtual-host: admin
        port: 5672
    jmx:
        enabled: false

eureka:
  instance:
    hostname: file-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
            defaultZone: http://localhost:8761/eureka/

fdfs:
  path: 192.192.0.49
  localPath: 192.192.0.49
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 192.192.0.49:22122

gridfs:
  path: 192.192.0.49:9000/file-service
  localPath: 192.192.0.49:9000/file-service

server:
    port: 9004
