spring:
    profiles:
        active: local
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    data:
        mongodb:
              uri: mongodb://pangolin:pangolin@192.191.0.41:27017
              database: pangolin_dataimp_db
    rabbitmq:
        username: admin
        password: admin
        host: 127.0.0.1
        virtual-host: admin
        port: 5672
    jmx:
        enabled: false

eureka:
  instance:
    hostname: file-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
            defaultZone: http://localhost:8761/eureka/

fdfs:
  path: 192.191.0.41
  localPath: 192.191.0.41
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 192.191.0.41:22122

gridfs:
  path: 192.191.0.41:9000/file-service
  localPath: 192.191.0.41:9000/file-service

server:
    port: 9004