server:
  port: 9000

spring:
  application:
    name: zuul-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000

zuul:
  host:
    socket-timeout-millis: 6000000
    connect-timeout-millis: 6000000