spring:
  profiles:
    active: local
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false # we use gulp + BrowserSync for livereload
  jackson:
    serialization.indent_output: true
    serialization.write_dates_as_timestamps: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.191.0.41:3306/pangolin_uat?useUnicode=true&characterEncoding=utf8&useSSL=false
    name:
    username: root
    password: root
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      connection-timeout: 36000
      validation-timeout: 3000
      maximum-pool-size: 250
      max-lifetime: 1800000
      idle-timeout: 60000
      leak-detection-threshold: 240000
      minimum-idle: 10
  rabbitmq:
    username: admin
    password: admin
    host: 192.191.0.41
    virtual-host: admin
    port: 5672
  cache:
    jcache:
      config: ehcache.xml
  redis:
    database: 4
    host: 192.191.0.41
    port: 6379
    expireTime: 3600
#        password: redis123456
eureka:
  instance:
    hostname: business-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9001

pangolin:
  companyCode: 1001
  tempFileDir: /usr/local/src/pangolin/temp
  UDesk:
    callerEmail: ceshi1007@51xf.cn
    secret: f2eef2a0f660cdd1a3841af2b58f0dd5
    callUrl: https://51xf.udesk.cn/


cuibei:
  baiduMap:
    webUrl: http://api.map.baidu.com/cloudgc/v1?city=全国&ak=
    webAk: lHaYCXlRADlhW0fnv8tpIhCfqD85pTSr

threadPool:
  corePoolSize: 400
  maxPoolSize: 500
  keepAliveSeconds : 60
  queueCapacity: 500
  allowCoreThreadTimeout : false
  threadNamePrefix: pangolin-

RSAPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCC09lmmyQ/xwGZ3ALAlxBhhAVX81EfAwIFnonavcJF6y5c4T8FC/YZSD4URcC7fyTmCZnwEiIAQhr33Qgineep5bY85LL4gWFlGis5FICbR0yj1Knl5JrZmCqtkK5uVItGwfb9iXYucAirhDtGdxBMurSid8o2y2wru6dXzQWrSQIDAQAB